@TmsApi_HostAddress = http://localhost:5117

### Test Assessments Results (requires auth)

GET {{TmsApi_HostAddress}}/api/assessments/results
Authorization: Bearer valid-token
Accept: application/json
###
GET {{TmsApi_HostAddress}}/api/enrollments/worker-smoke
Authorization: Bearer valid-token
Accept: application/json

###




### Test Weather Forecast
GET {{TmsApi_HostAddress}}/weatherforecast
Accept: application/json

### Get All Enrollments
GET {{TmsApi_HostAddress}}/api/enrollment
Authorization: Bearer valid-token
Accept: application/json

###

### Create New Enrollment
POST {{TmsApi_HostAddress}}/api/enrollment
Authorization: Bearer valid-token
Content-Type: application/json

{
  "studentId": "S-001",
  "courseCode": "CS-101"
}

###

### Get Enrollment by ID
GET {{TmsApi_HostAddress}}/api/enrollment/REPLACE_WITH_ID
Authorization: Bearer valid-token
Accept: application/json

###

### Delete Enrollment
DELETE {{TmsApi_HostAddress}}/api/enrollment?id=REPLACE_WITH_ID
Authorization: Bearer valid-token

///
/// Note: 
/// 1. Replace REPLACE_WITH_ID with an actual enrollment ID from the Get All Enrollments response
/// 2. Click "Send Request" on any block to test that endpoint
/// 3. View responses in the panel on the right


